server:
  port: 8084
  tomcat:
    accesslog:
      buffered: true
      directory: D:/booking_client_tomcat
      enabled: true
      file-date-format: .yyyy-MM-dd
      pattern: common
      prefix: access_log
      rename-on-rotate: false
      request-attributes-enabled: false
      rotate: true
      suffix: .log
# 上传文件相关
file:
  uploadFolder: E:/booking/
  #对外访问的资源路径
  staticAccessPath: /booking/**
  server_ip: http://127.0.0.1:8084/
#spring
spring:
  aop:
    proxy-target-class: true
  datasource: #database
    master:  # common Datasource
      jdbc-url: jdbc:mysql://171.15.132.248:3306/booking_platform_system_test?useUnicodle=true&characterEncoding=utf8&useSSL=false
      username: szhbl
      password: Szhbl@20200106
#      jdbc-url: jdbc:mysql://123.56.11.19:3306/booking_platform_system?useUnicodle=true&characterEncoding=utf8&useSSL=false&useTimezone=false&serverTimezone=GMT%2B8
#      username: root
#      password: Shy!123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource
      druid:
       initial-size: 8
       min-idle: 1
       max-active: 20
       max-wait: 60000
       time-between-eviction-runsMillis: 60000
       min-evictable-idle-timeMillis: 300000
       validation-query: select 'x' FROM DUAL
       test-while-idle: true
       test-on-borrow: false
       test-on-return: false
       pool-prepared-statements: true
       max-open-prepared-statements: 20
       max-pool-prepared-statement-per-connection-size: 20
       filters: stat
       connection-properties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
       use-global-data-source-stat: true
#    slave:  # js Datasource
#      jdbc-url: jdbc:sqlserver://218.28.14.158:11433;DatabaseName=test0914
#      username: FCCDtwfdjkk
#      password: DC19Lu02GJzh0k,Gang.27ZL
#      driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  # Redis配置
  redis:
    host: 171.15.132.175
    port: 6379
    password: banlie123
    timeout: 10s
  rabbitmq:
    host: 218.28.14.160
#     host: 127.0.0.1
    username: guest
    password: guest
    publisher-confirms: true
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        concurrency: 1
        max-concurrency: 1
        retry:
          enabled: true
      direct:
        acknowledge-mode: manual
  mail:
    host: smtp.qiye.163.com #发送邮件服务器
    username: booking@zih718.com #发送邮件的邮箱地址
    password: UD6VqLfJRq2yhDwJ #客户端授权码，不是邮箱密码,网易的是自己设置的
    properties:
      mail:
        smtp:
          port: 994 #465或者994
          starttls:
            enable: true
            required: true
          ssl:
            enable: true
    from: booking@zih718.com # 发送邮件的地址，和上面username一致 可以任意s
    default-encoding: utf-8
#mybatis
mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml,classpath*:/settlementMapper/**Mapper.xml
  #实体扫描，多个package用逗号或者分号分隔
  typeAliasesPackage: com.zih.booking.model
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
    id-type: 0
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    #字段策略 0:"忽略判断",1:"非 NULL 判断"),2:"非空判断"
    field-strategy: 1
    #驼峰下划线转换
    db-column-underline: true
    #刷新mapper 调试神器
    refresh-mapper: true
    #数据库大写下划线转换
    #capital-mode: true
    #序列接口实现类配置
    #key-generator: com.baomidou.springboot.xxx
    #逻辑删除配置（下面3个配置）
    logic-delete-value: 1
    logic-not-delete-value: 0
    #自定义SQL注入器
    sql-injector: com.baomidou.mybatisplus.mapper.LogicSqlInjector
    #自定义填充策略接口实现
    #meta-object-handler: com.zih.booking.system.handler.MyMetaObjectHandler
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false

logging:
  level:
    root: error
    org.springframework:  error
    org.mybatis:  error
    com.zih.booking: debug
    com.zih: info
  path: d:/booking_client_log
  file:
    max-size: 200MB
# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌秘钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30

inquiry:
  del: "40尺分层箱"
dcSystem:
  domainName: http://171.15.132.176:8082